version: "3"
services:
  scylla-rdf-pipelines:
    build: ./
    image: datafabricrus/scylla-rdf-pipelines:0.0.1
    environment:
      - SCYLLA_HOSTS=scylla # E.g. 10.0.0.1,10.0.0.1
    volumes:
      - "./upload:/upload"
    command: ./run_bulkload_flink.sh --source=/upload/* # E.g. --source=/upload/file.ttl,/upload/folder1/file.nt
    #command: ./run_fulltext_flink.sh --source=/upload/* # E.g. --source=/upload/file.ttl,/upload/folder1/file.nt