#!/usr/bin/env bash

SCYLLA_RDF_PIPELINES_JAR="${SCYLLA_RDF_PIPELINES_JAR:-target/scylladb-pipelines-1.0-SNAPSHOT.jar}"
SCYLLA_RDF_STORAGE_HOSTS="${SCYLLA_RDF_STORAGE_HOSTS:-localhost}"
SCYLLA_RDF_STORAGE_PORT="${SCYLLA_RDF_STORAGE_PORT:-9042}"
SCYLLA_RDF_STORAGE_KEYSPACE="${SCYLLA_RDF_STORAGE_KEYSPACE:-triplestore}"

java -jar ${SCYLLA_RDF_PIPELINES_JAR} --runner=FlinkRunner --hosts=${SCYLLA_RDF_STORAGE_HOSTS} \
    --port=${SCYLLA_RDF_STORAGE_PORT} --keyspace=${SCYLLA_RDF_STORAGE_KEYSPACE} \
    --batchSize=500000 $@