#!/usr/bin/env bash

PIPELINE_JAR="${PIPELINE_JAR:-target/scylla-rdf-pipelines-0.0.1-SNAPSHOT.jar}"
PIPELINE_BATCH_SIZE="${PIPELINE_BATCH_SIZE:-10000}"

SCYLLA_HOSTS="${SCYLLA_HOSTS:-localhost}"
SCYLLA_PORT="${SCYLLA_PORT:-9042}"
SCYLLA_KEYSPACE="${SCYLLA_KEYSPACE:-triplestore}"
SCYLLA_MAX_REQUESTS_PER_CONNECTION="${SCYLLA_MAX_REQUESTS_PER_CONNECTION:-32}"

java -jar ${PIPELINE_JAR} --runner=FlinkRunner --hosts=${SCYLLA_HOSTS} \
    --port=${SCYLLA_PORT} --keyspace=${SCYLLA_KEYSPACE} \
    --maxRequestsPerConnection=${SCYLLA_MAX_REQUESTS_PER_CONNECTION} \
    --batchSize=${PIPELINE_BATCH_SIZE} $@